lidar_node:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    serial_baud: 115200
    laser_frame_id: "laser"

rgbd_camera_node:
  ros__parameters:
    camera_name: "camera"
    rgb_camera.profile: 1280X720X30
    pointcloud.enable: true

apriltag:
  ros__parameters:
      image_transport: compressed    # image format
      family: 36h11           # tag family name
      size: 0.0865             # tag edge size in meter
      max_hamming: 0          # maximum allowed hamming distance (corrected bits)
      z_up: false              # rotate about x-axis to have Z pointing upwards

      # see "apriltag.h" for more documentation on these optional parameters
      decimate: 1.0           # decimate resolution for quad detection
      blur: 0.0               # sigma of Gaussian blur for quad detection
      refine-edges: 1         # snap to strong gradients
      threads: 1              # number of threads
      refine-decode: 0        # increase the number of detected tags
      refine-pose: 0          # increase the accuracy of the extracted pose
      debug: 0                # write additional debugging images to current working directory